"""Run this once to seed/update all activity types from T04 regulation."""

import sys
import os

sys.path.insert(0, os.path.dirname(__file__))
from database import get_connection

ACTIVITIES = [
    # category: Giảng dạy (is_teaching=1) — ALL emp types
    (
        "GD - Lý thuyết ĐH (dùng class_level+student_count để nhân hệ số)",
        "Giảng dạy",
        "Tiết",
        1.0,
        1,
        0,
        "ALL",
    ),
    ("GD - Thực hành ĐH nhiều GV (0.7/GV)", "Giảng dạy", "Tiết", 0.7, 1, 0, "ALL"),
    ("GD - BD Cơ bản/Chỉ huy đội/Ngạch sơ cấp", "Bồi dưỡng", "Tiết", 1.0, 1, 0, "ALL"),
    ("GD - BD Trưởng/Phó CA xã", "Bồi dưỡng", "Tiết", 1.3, 1, 0, "ALL"),
    (
        "GD - BD Lãnh đạo phòng/Ngạch trung cấp/Chuyên sâu",
        "Bồi dưỡng",
        "Tiết",
        1.5,
        1,
        0,
        "ALL",
    ),
    (
        "GD - BD Lãnh đạo cấp Cục/Ngạch cao cấp/Chuyên gia",
        "Bồi dưỡng",
        "Tiết",
        2.0,
        1,
        0,
        "ALL",
    ),
    ("GD - Tiếng nước ngoài ≤40 HV", "Giảng dạy", "Tiết", 1.5, 1, 0, "ALL"),
    ("GD - Tiếng nước ngoài 41-60 HV", "Giảng dạy", "Tiết", 1.7, 1, 0, "ALL"),
    ("GD - Tiếng nước ngoài >60 HV", "Giảng dạy", "Tiết", 2.0, 1, 0, "ALL"),
    ("GD - Hướng dẫn thực tập TN", "Giảng dạy", "Ngày", 2.5, 1, 0, "ALL"),
    ("GD - Hướng dẫn KL ĐH (đạt)", "Giảng dạy", "KL", 15.0, 1, 0, "ALL"),
    ("GD - Hướng dẫn KL ĐH NN (đạt)", "Giảng dạy", "KL", 20.0, 1, 0, "ALL"),
    ("GD - Hướng dẫn KL LLCT (đạt)", "Giảng dạy", "KL", 15.0, 1, 0, "ALL"),
    ("GD - Hướng dẫn LV ThS (đạt)", "Giảng dạy", "LV", 30.0, 1, 0, "ALL"),
    ("GD - Hướng dẫn LV ThS NN (đạt)", "Giảng dạy", "LV", 40.0, 1, 0, "ALL"),
    ("GD - Hướng dẫn NCS (chính, mỗi năm)", "Giảng dạy", "NCS/năm", 50.0, 1, 0, "ALL"),
    ("GD - Hướng dẫn NCS (phụ, mỗi năm)", "Giảng dạy", "NCS/năm", 25.0, 1, 0, "ALL"),
    # category: Hoạt động chuyên môn — TEACHER,STAFF only
    (
        "NVK - Bài dạy giỏi cấp khoa",
        "Hoạt động chuyên môn",
        "Bài",
        10.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Bài dạy giỏi cấp trường",
        "Hoạt động chuyên môn",
        "Bài",
        15.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Bài dạy giỏi cấp bộ",
        "Hoạt động chuyên môn",
        "Bài",
        20.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - HĐ đánh giá dạy giỏi cấp khoa/buổi",
        "Hoạt động chuyên môn",
        "Buổi",
        2.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - HĐ đánh giá dạy giỏi cấp trường/buổi",
        "Hoạt động chuyên môn",
        "Buổi",
        3.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - HĐ đánh giá dạy giỏi cấp bộ/buổi",
        "Hoạt động chuyên môn",
        "Buổi",
        5.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Biên soạn đề thi TL kết thúc HP",
        "Hoạt động chuyên môn",
        "Đề",
        1.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Biên soạn đề thi VĐ/TH kết thúc HP",
        "Hoạt động chuyên môn",
        "Đề",
        0.125,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Biên soạn đề thi TN kết thúc HP",
        "Hoạt động chuyên môn",
        "Đề",
        0.1,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Biên soạn đề thi TN/TS TL",
        "Hoạt động chuyên môn",
        "Đề",
        2.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Biên soạn đề thi TN/TS VĐ/TH",
        "Hoạt động chuyên môn",
        "Đề",
        0.25,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Biên soạn đề thi TN/TS TN",
        "Hoạt động chuyên môn",
        "Đề",
        0.2,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Coi thi kết thúc HP",
        "Hoạt động chuyên môn",
        "Buổi",
        1.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Coi thi TN/tuyển sinh",
        "Hoạt động chuyên môn",
        "Buổi",
        1.5,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Phục vụ kỹ thuật thi TH máy tính",
        "Hoạt động chuyên môn",
        "Buổi",
        1.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - HĐ thi TN/tuyển sinh họp",
        "Hoạt động chuyên môn",
        "Buổi",
        2.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Làm phách bài thi",
        "Hoạt động chuyên môn",
        "Bài",
        0.02,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm thi TL kết thúc HP",
        "Hoạt động chuyên môn",
        "Bài",
        0.125,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm thi VĐ/TH kết thúc HP",
        "Hoạt động chuyên môn",
        "Bài",
        0.1,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm thi TN kết thúc HP",
        "Hoạt động chuyên môn",
        "Bài",
        0.05,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm tiểu luận thay thi HP",
        "Hoạt động chuyên môn",
        "TL",
        1.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm thi TN/TS TL hoặc VĐ/TH",
        "Hoạt động chuyên môn",
        "Bài",
        0.1667,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm thi TN/TS trắc nghiệm",
        "Hoạt động chuyên môn",
        "Bài",
        0.0833,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm báo cáo thực tập/thực hành CT",
        "Hoạt động chuyên môn",
        "BC",
        1.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - HĐ duyệt tên KL ĐH - Chủ tịch",
        "Hoạt động chuyên môn",
        "KL",
        1.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - HĐ duyệt tên KL ĐH - Thành viên",
        "Hoạt động chuyên môn",
        "KL",
        0.7,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Đọc nhận xét KL ĐH",
        "Hoạt động chuyên môn",
        "KL",
        3.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Đọc nhận xét KL ĐH tiếng NN",
        "Hoạt động chuyên môn",
        "KL",
        4.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm bảo vệ KL ĐH - Chủ tịch",
        "Hoạt động chuyên môn",
        "KL",
        3.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm bảo vệ KL ĐH - Thành viên",
        "Hoạt động chuyên môn",
        "KL",
        2.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm bảo vệ KL ĐH tiếng NN - Chủ tịch",
        "Hoạt động chuyên môn",
        "KL",
        5.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm bảo vệ KL ĐH tiếng NN - Thành viên",
        "Hoạt động chuyên môn",
        "KL",
        4.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Đọc nhận xét KL LLCT",
        "Hoạt động chuyên môn",
        "KL",
        3.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm bảo vệ KL LLCT - Chủ tịch",
        "Hoạt động chuyên môn",
        "KL",
        3.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm bảo vệ KL LLCT - Thành viên",
        "Hoạt động chuyên môn",
        "KL",
        2.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - HĐ duyệt tên LV ThS - Chủ tịch",
        "Hoạt động chuyên môn",
        "LV",
        1.5,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - HĐ duyệt tên LV ThS - Thành viên",
        "Hoạt động chuyên môn",
        "LV",
        1.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Phản biện LV ThS",
        "Hoạt động chuyên môn",
        "LV",
        6.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Đọc nhận xét LV ThS - Thành viên",
        "Hoạt động chuyên môn",
        "LV",
        3.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm bảo vệ LV ThS - CT/PB/TK",
        "Hoạt động chuyên môn",
        "LV",
        4.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm bảo vệ LV ThS - Thành viên",
        "Hoạt động chuyên môn",
        "LV",
        3.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - HĐ duyệt tên LA TS - Chủ tịch",
        "Hoạt động chuyên môn",
        "LA",
        2.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - HĐ duyệt tên LA TS - Thành viên",
        "Hoạt động chuyên môn",
        "LA",
        1.5,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm chuyên đề TS",
        "Hoạt động chuyên môn",
        "CĐ",
        3.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Hội thảo LA TS - CT/TK",
        "Hoạt động chuyên môn",
        "LA",
        7.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Hội thảo LA TS - Thành viên",
        "Hoạt động chuyên môn",
        "LA",
        5.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Phản biện LA TS",
        "Hoạt động chuyên môn",
        "LA",
        10.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Đọc nhận xét LA TS - Thành viên",
        "Hoạt động chuyên môn",
        "LA",
        5.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm bảo vệ LA cấp cơ sở - CT/PB/TK",
        "Hoạt động chuyên môn",
        "LA",
        10.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm bảo vệ LA cấp cơ sở - Thành viên",
        "Hoạt động chuyên môn",
        "LA",
        6.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm bảo vệ LA cấp trường - CT/PB/TK",
        "Hoạt động chuyên môn",
        "LA",
        12.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    (
        "NVK - Chấm bảo vệ LA cấp trường - Thành viên",
        "Hoạt động chuyên môn",
        "LA",
        8.0,
        0,
        0,
        "TEACHER,STAFF",
    ),
    # category: Chấp hành Nhiệm vụ khác (free-form) — ALL
    (
        "CHNVK - Chấp hành nhiệm vụ khác (tự khai báo)",
        "Chấp hành Nhiệm vụ khác",
        "Giờ",
        1.0,
        0,
        0,
        "ALL",
    ),
    # category: NCKH (is_nckh=1) — TEACHER,STAFF only
    ("NCKH - Bài báo ISI/Scopus", "NCKH", "Bài", 1000.0, 0, 1, "TEACHER,STAFF"),
    ("NCKH - Bài báo ISSN 1.0đ", "NCKH", "Bài", 600.0, 0, 1, "TEACHER,STAFF"),
    ("NCKH - Bài báo ISSN 0.75đ", "NCKH", "Bài", 450.0, 0, 1, "TEACHER,STAFF"),
    ("NCKH - Bài báo ISSN 0.5đ", "NCKH", "Bài", 300.0, 0, 1, "TEACHER,STAFF"),
    ("NCKH - Bài báo ISSN 0.25đ", "NCKH", "Bài", 150.0, 0, 1, "TEACHER,STAFF"),
    (
        "NCKH - Bài báo ISSN (ngoài danh mục)",
        "NCKH",
        "Bài",
        150.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "NCKH - Đề tài cấp Quốc gia (mỗi năm)",
        "NCKH",
        "Đề tài/năm",
        1200.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "NCKH - Đề tài cấp Bộ/Tỉnh (mỗi năm)",
        "NCKH",
        "Đề tài/năm",
        1200.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    ("NCKH - Đề tài cấp Cơ sở", "NCKH", "Đề tài", 1200.0, 0, 1, "TEACHER,STAFF"),
    ("NCKH - Chuyên đề KH cấp trường", "NCKH", "CĐ", 600.0, 0, 1, "TEACHER,STAFF"),
    ("NCKH - Sáng kiến cấp Quốc gia", "NCKH", "SK", 1200.0, 0, 1, "TEACHER,STAFF"),
    ("NCKH - Sáng kiến cấp Bộ/Tỉnh", "NCKH", "SK", 900.0, 0, 1, "TEACHER,STAFF"),
    ("NCKH - Sáng kiến cấp Cơ sở", "NCKH", "SK", 600.0, 0, 1, "TEACHER,STAFF"),
    ("NCKH - Giáo trình biên soạn mới", "NCKH", "GT", 1200.0, 0, 1, "TEACHER,STAFF"),
    ("NCKH - Sách chuyên khảo", "NCKH", "Sách", 900.0, 0, 1, "TEACHER,STAFF"),
    ("NCKH - Sách tham khảo", "NCKH", "Sách", 600.0, 0, 1, "TEACHER,STAFF"),
    ("NCKH - Sách hướng dẫn/đề cương/CTĐT", "NCKH", "TL", 450.0, 0, 1, "TEACHER,STAFF"),
    (
        "NCKH - Báo cáo NCKH toàn văn kỷ yếu cấp trường",
        "NCKH",
        "Bài",
        150.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "NCKH - Báo cáo NCKH toàn văn kỷ yếu cấp bộ",
        "NCKH",
        "Bài",
        300.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "NCKH - Báo cáo NCKH toàn văn kỷ yếu cấp quốc gia",
        "NCKH",
        "Bài",
        600.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "NCKH - Báo cáo NCKH toàn văn kỷ yếu quốc tế",
        "NCKH",
        "Bài",
        900.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "NCKH - Hướng dẫn HV NCKH đạt yêu cầu cấp trường",
        "NCKH",
        "HV",
        16.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "NCKH - Hướng dẫn HV NCKH giải KK cấp trường",
        "NCKH",
        "HV",
        20.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "NCKH - Hướng dẫn HV NCKH giải Ba cấp trường",
        "NCKH",
        "HV",
        24.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "NCKH - Hướng dẫn HV NCKH giải Nhì cấp trường",
        "NCKH",
        "HV",
        32.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "NCKH - Hướng dẫn HV NCKH giải Nhất cấp trường",
        "NCKH",
        "HV",
        40.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "NCKH - Hướng dẫn HV NCKH đạt yêu cầu cấp bộ",
        "NCKH",
        "HV",
        32.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "NCKH - Hướng dẫn HV NCKH giải KK cấp bộ",
        "NCKH",
        "HV",
        40.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "NCKH - Hướng dẫn HV NCKH giải Ba cấp bộ",
        "NCKH",
        "HV",
        56.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "NCKH - Hướng dẫn HV NCKH giải Nhì cấp bộ",
        "NCKH",
        "HV",
        64.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "NCKH - Hướng dẫn HV NCKH giải Nhất cấp bộ",
        "NCKH",
        "HV",
        72.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    ("NCKH - Cải tiến cấp trường", "NCKH", "CT", 300.0, 0, 1, "TEACHER,STAFF"),
    ("NCKH - Cải tiến cấp bộ", "NCKH", "CT", 450.0, 0, 1, "TEACHER,STAFF"),
    # Competition activities — TEACHER,STAFF only
    (
        "Hướng dẫn HV thi cấp trường - Đạt yêu cầu",
        "NCKH - Hướng dẫn thi đấu",
        "HV",
        16.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "Hướng dẫn HV thi cấp trường - Giải Khuyến khích",
        "NCKH - Hướng dẫn thi đấu",
        "HV",
        20.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "Hướng dẫn HV thi cấp trường - Giải Ba",
        "NCKH - Hướng dẫn thi đấu",
        "HV",
        24.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "Hướng dẫn HV thi cấp trường - Giải Nhì",
        "NCKH - Hướng dẫn thi đấu",
        "HV",
        32.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "Hướng dẫn HV thi cấp trường - Giải Nhất",
        "NCKH - Hướng dẫn thi đấu",
        "HV",
        40.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "Hướng dẫn HV thi cấp bộ - Đạt yêu cầu",
        "NCKH - Hướng dẫn thi đấu",
        "HV",
        32.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "Hướng dẫn HV thi cấp bộ - Giải Khuyến khích",
        "NCKH - Hướng dẫn thi đấu",
        "HV",
        40.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "Hướng dẫn HV thi cấp bộ - Giải Ba",
        "NCKH - Hướng dẫn thi đấu",
        "HV",
        56.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "Hướng dẫn HV thi cấp bộ - Giải Nhì",
        "NCKH - Hướng dẫn thi đấu",
        "HV",
        64.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
    (
        "Hướng dẫn HV thi cấp bộ - Giải Nhất",
        "NCKH - Hướng dẫn thi đấu",
        "HV",
        72.0,
        0,
        1,
        "TEACHER,STAFF",
    ),
]


def run():
    conn = get_connection()
    cursor = conn.cursor()
    added, updated = 0, 0
    for a in ACTIVITIES:
        cursor.execute(
            """
            INSERT INTO activity_types (name, category, unit, base_conversion_rate, is_teaching_activity, is_nckh_activity, applicable_employment_types)
            VALUES (?,?,?,?,?,?,?)
            ON CONFLICT(name) DO UPDATE SET
                category = excluded.category,
                unit = excluded.unit,
                base_conversion_rate = excluded.base_conversion_rate,
                is_teaching_activity = excluded.is_teaching_activity,
                is_nckh_activity = excluded.is_nckh_activity,
                applicable_employment_types = excluded.applicable_employment_types
        """,
            a,
        )
        if cursor.rowcount == 1:
            added += 1
        else:
            updated += 1
    conn.commit()
    conn.close()
    print(f"Done. Added: {added}, Updated (existing): {updated}")


if __name__ == "__main__":
    run()
