[server]
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[theme]
base = "light"
primaryColor = "#006747"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f2f3fc"
textColor = "#191c21"
